Entity/Question.php
<?php

namespace DSYSurveyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Description of Question.
 *
 * @ORM\Table(name="srv_question")
 * @ORM\Entity(repositoryClass="DSYSurveyBundle\Repository\QuestionRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 *     "question" = "Question",
 *     "text" = "TextQuestion",
 *     "bool" = "BooleanQuestion",
 *     "multiplechoice" = "MultipleChoiceQuestion",
 * })
 *
 * @author snake77se <yosip.curiel@dsarhoya.cl>
 */
class Question implements EntityEnabledInterface
{
    const TYPE_TEXT = 'text';
    const TYPE_BOOLEAN = 'bool';
    const TYPE_MULTIPLE_CHOICE = 'multiplechoice';
    const TYPE_SINGLE_CHOICE = 'singlechoice';
    const TYPE_GROUP_CHOICE = 'groupchoice';
    const TYPE_SINGLE_AUTOCOMPLETE = 'singleautocomplete';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @JMS\SerializedName("id")
     * @JMS\Groups({"question_list", "question_detail"})
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string")
     * @Assert\NotBlank()
     * @JMS\SerializedName("title")
     * @JMS\Groups({"question_list", "question_detail"})
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     * @JMS\SerializedName("description")
     * @JMS\Groups({"question_detail"})
     */
    protected $description;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     * @JMS\SerializedName("code")
     * @JMS\Groups({"question_detail"})
     */
    protected $code;

    /**
     * @var bool
     *
     * @ORM\Column(name="mandatory", type="boolean", options={"default":true})
     * @JMS\SerializedName("mandatory")
     * @JMS\Groups({"question_detail"})
     */
    protected $mandatory = true;

    /**
     * @var int
     *
     * @Gedmo\SortablePosition
     * @ORM\Column(name="position", type="integer", nullable=true)
     * @JMS\SerializedName("position")
     * @JMS\Groups({"question_detail"})
     */
    protected $position;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     * @JMS\SerializedName("created_at")
     * @JMS\Groups({"question_detail"})
     */
    protected $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     * @JMS\SerializedName("updated_at")
     * @JMS\Groups({"question_detail"})
     */
    protected $updatedAt;

    /**
     * @var Page
     *
     * @ORM\ManyToOne(targetEntity="Page", inversedBy="questions")
     * @ORM\JoinColumn(name="page_id", referencedColumnName="id")
     * @Gedmo\SortableGroup
     * @JMS\SerializedName("page")
     * @JMS\Groups({"r_question_page"})
     */
    protected $page;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default": 1})
     * @JMS\SerializedName("enabled")
     * @JMS\Groups({"question_list", "question_detail"})
     * @Gedmo\SortableGroup
     */
    protected $enabled = true;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default": 0})
     * @JMS\SerializedName("has_comments")
     * @JMS\Groups({"question_detail"})
     */
    protected $hasComments = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default": 0})
     * @JMS\SerializedName("has_images")
     * @JMS\Groups({"question_detail"})
     */
    protected $hasImages = false;

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->title;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return Question
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return Question
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set position.
     *
     * @param int $position
     *
     * @return Question
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position.
     *
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * @throws \Exception Método "getType" en Entidad "Question" no implementado
     *
     * @return string
     */
    public function getType()
    {
        return new \Exception('Método "getType" en Entidad "Question" no implementado');
    }

    /**
     * @throws \Exception Método "getDiscriminatorColumn" en Entidad "Question" no implementado
     *
     * @return string
     */
    public function getDiscriminatorColumn()
    {
        return new \Exception('Método "getDiscriminatorColumn" en Entidad "Question" no implementado');
    }

    /**
     * Set mandatory.
     *
     * @param bool $mandatory
     *
     * @return Question
     */
    public function setMandatory($mandatory)
    {
        $this->mandatory = $mandatory;

        return $this;
    }

    /**
     * Get mandatory.
     *
     * @return bool
     */
    public function getMandatory()
    {
        return $this->mandatory;
    }

    /**
     * Sets createdAt.
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Returns createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Sets updatedAt.
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Returns updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Get page ID.
     *
     * @JMS\VirtualProperty
     * @JMS\SerializedName("page_id")
     * @JMS\Groups({"question_detail"})
     *
     * @return int
     */
    public function getPageId()
    {
        return null !== $this->page ? $this->page->getId() : null;
    }

    /**
     * Set page.
     *
     * @return Question
     */
    public function setPage(\DSYSurveyBundle\Entity\Page $page = null)
    {
        $this->page = $page;

        if (null !== $page) {
            $page->addQuestion($this);
        }

        return $this;
    }

    /**
     * Get page.
     *
     * @return \DSYSurveyBundle\Entity\Page|null
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Set code.
     *
     * @param string|null $code
     *
     * @return Question
     */
    public function setCode($code = null)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * set enabled.
     *
     * @return self
     */
    public function setEnabled(bool $state)
    {
        $this->enabled = $state;

        return $this;
    }

    /**
     * Get enabled.
     *
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * Get code.
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * typesNames.
     *
     * @return array
     */
    public static function typesNames()
    {
        return [
            self::TYPE_BOOLEAN => 'Sí o no',
            self::TYPE_TEXT => 'Texto',
            self::TYPE_MULTIPLE_CHOICE => 'Selección múltiple',
            self::TYPE_SINGLE_CHOICE => 'Selección única',
            self::TYPE_GROUP_CHOICE => 'Grupo de Selección',
            self::TYPE_SINGLE_AUTOCOMPLETE => 'Seleccion única (Autocompletado)',
        ];
    }

    /**
     * getTypeName.
     *
     * @return string
     */
    public function getTypeName()
    {
        $names = self::typesNames();

        return null !== $this->getType() ? $names[$this->getType()] : self::TYPE_MULTIPLE_CHOICE;
    }

    /**
     * Get the value of hasComments.
     *
     * @return bool
     */
    public function hasComments()
    {
        return $this->hasComments;
    }

    /**
     * Set the value of hasComments.
     *
     * @return self
     */
    public function setHasComments(bool $hasComments)
    {
        $this->hasComments = $hasComments;

        return $this;
    }

    /**
     * Get the value of hasImages.
     *
     * @return bool
     */
    public function hasImages()
    {
        return $this->hasImages;
    }

    /**
     * Set the value of hasImages.
     *
     * @return self
     */
    public function setHasImages(bool $hasImages)
    {
        $this->hasImages = $hasImages;

        return $this;
    }
}

Form/Web/FlowExceptionType.php
<?php

namespace DSYSurveyBundle\Form\Web;

use DSYSurveyBundle\Entity\FlowException;
use DSYSurveyBundle\Entity\MultipleChoiceQuestion;
use DSYSurveyBundle\Entity\MultipleChoiceQuestionAlternative;
use DSYSurveyBundle\Entity\Question;
use DSYSurveyBundle\Form\ButtonsGroupsType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * FlowException Type.
 *
 * @author snake77se <yosip.curiel@dsarhoya.cl>
 */
class FlowExceptionType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /** @var FlowException $exception */
        $exception = $builder->getData();
        $builder
            ->add('newFlow', EntityType::class, [
                'label' => 'Siguiente pregunta',
                'class' => Question::class,
                'choices' => $options['questions'],
                'choice_label' => function (Question $choice) {
                    return 'Página '.$choice->getPage()->getCode().', Pregunta "'.(null !== $choice->getCode() ? $choice->getCode() : $choice->getTitle()).'"';
                },
                'placeholder' => 'Pregunta Final',
                'required' => false,
                'group_by' => function (Question $choice) {
                    return $choice->getPage()->getSection()->getName();
                },
            ]);

        $question = $exception->getQuestion();
        if ($question instanceof MultipleChoiceQuestion && in_array($question->getType(), [Question::TYPE_SINGLE_CHOICE/* , Question::TYPE_SINGLE_AUTOCOMPLETE */])) {
            $builder
                ->add('alternative', EntityType::class, [
                    'label' => 'Alternativa',
                    'placeholder' => 'Todas',
                    'required' => false,
                    'class' => MultipleChoiceQuestionAlternative::class,
                    'choices' => $question->getAlternativesEnabled(),
                    'choice_label' => 'title',
                ]);
        }

        $builder->add('buttons', ButtonsGroupsType::class, [
            'cancel_link' => $options['cancel_link'],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FlowException::class,
        ])->setRequired('questions')->setRequired('cancel_link');
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'dsysurveybundle_flow_exception';
    }
}

Controller/Web/FlowExceptionController.php
<?php

namespace DSYSurveyBundle\Controller\Web;

use Doctrine\ORM\EntityRepository;
use DSYSurveyBundle\Controller\AbstractSurveyController;
use DSYSurveyBundle\Entity\FlowException;
use DSYSurveyBundle\Entity\Page;
use DSYSurveyBundle\Entity\Question;
use DSYSurveyBundle\Entity\Section;
use DSYSurveyBundle\Entity\Survey;
use DSYSurveyBundle\Event\DSYSurveyBundleEvents;
use DSYSurveyBundle\Event\GetFlowExceptionBackUrlEvent;
use DSYSurveyBundle\Form\Web\FlowExceptionType;
use DSYSurveyBundle\Repository\FlowExceptionRepository;
use DSYSurveyBundle\Repository\QuestionRepository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * FlowException Controller.
 *
 * @Route("/questions/{question}/flow-exceptions")
 *
 * @author snake77se <yosip.curiel@dsarhoya.cl>
 */
class FlowExceptionController extends AbstractSurveyController
{
    /**
     * index.
     *
     * @Route("/", name="dsy_survey_section_page_question_flow_exception_index", methods={"GET","POST"})
     * @Route("/{exception}/edit", name="dsy_survey_section_page_question_flow_exception_edit", methods={"GET", "POST"}, defaults={"exception"=null})
     *
     * @param int|null $exception
     *
     * @return Response
     */
    public function indexAction(Request $request, Question $question, $exception = null)
    {
        $page = $question->getPage();
        $section = $page->getSection();
        $survey = $section->getSurvey();

        if (null !== $exception) {
            /** @var FlowExceptionRepository $exceptionRepo */
            $exceptionRepo = $this->getDoctrine()->getManager()->getRepository(FlowException::class);
            $exception = $exceptionRepo->find($exception);
        }

        $new = false;
        if (null === $exception) {
            $new = true;
            $exception = new FlowException($question);
        }

        /** @var QuestionRepository $questionRepo */
        $questionRepo = $this->getDoctrine()->getManager()->getRepository(Question::class);
        $questions = $questionRepo->questions($survey);

        $options = [
            'questions' => $questions,
            'cancel_link' => $this->generateUrl('dsy_survey_section_page_question_flow_exception_index', ['question' => $question->getId()]),
        ];

        $form = $this->createForm(FlowExceptionType::class, $exception, $options);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            if ($new) {
                $em->persist($exception);
            }
            $em->flush();
            $this->flashSuccess(sprintf('Excepción %s exitosamente.', $new ? 'creada' : 'actualizada'));

            return $this->redirectToRoute('dsy_survey_section_page_question_flow_exception_index', ['question' => $question->getId()]);
        }

        $event = new GetFlowExceptionBackUrlEvent($exception);
        $this->dispatcher()->dispatch($event, DSYSurveyBundleEvents::GET_FLOW_EXCEPTION_BACK_URL);
        $backlUrl = $event->getBackUrl();

        /** @var EntityRepository $repo */
        $repo = $this->getDoctrine()->getManager()->getRepository(FlowException::class);
        $exceptions = $repo->findByQuestion($question);

        $form = $form->createView();

        return $this->render('@DSYSurvey/Web/flow_exception/index.html.twig', compact('survey', 'section', 'page', 'question', 'exceptions', 'questions', 'form', 'exception', 'backlUrl'));
    }

    /**
     * delete flow exception.
     *
     * @Route("/{exception}/delete", name="dsy_survey_section_page_question_flow_exception_delete", methods={"GET"})
     *
     * @return RedirectResponse
     */
    public function deleteAction(Question $question, FlowException $exception)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($exception);
        $em->flush();

        $this->flashSuccess('Excepción borrada exitosamente.');

        return $this->redirectToRoute('dsy_survey_section_page_question_flow_exception_index', ['question' => $question->getId()]);
    }
}

Resources/views/Web/flow_exception/_preview_questions_flow.html.twig
<div class="row mb-3">
    <div class="col">
        <h4>Flujo de preguntas</h4>
    </div>
</div>

{% for q in questions %}
    {% set page = q.page %}
    {% set section = page.section %}
    {% set survey = section.survey %}
    {% set avaribleQuestionType = [constant('DSYSurveyBundle\\Entity\\Question::TYPE_SINGLE_CHOICE')] %}{# , constant('DSYSurveyBundle\\Entity\\Question::TYPE_SINGLE_AUTOCOMPLETE') #}
    {% if q.type not in avaribleQuestionType or not hasAlternativeFlowExceptions(q) %}
        {% set nextQuestion = nextQuestion(q) %}
        <div class="row">
            <div class="col-5 px-0">
                <span class="badge badge-success" title="Pregunta de {{ q.typeName }}">{{ q|firstLetterType }}</span>
                <a class="link" title="Editar pregunta" href="{{ path('dsy_survey_section_page_question_edit', { survey: survey.id, section: section.id, page: page.id, question: q.id}) }}">
                    <span>{{ q.code is not null ? q.code|upper : q.title|capitalize }}</span>
                </a>
            </div>
            <div class="col-2 text-center px-0">>></div>
            <div class="col-5 text-right px-0">
                {% if nextQuestion is not null %}
                    <span class="badge badge-success" title="Pregunta de {{ nextQuestion.typeName }}">{{ nextQuestion|firstLetterType }}</span>
                    <a class="link" title="Editar pregunta" href="{{ path('dsy_survey_section_page_question_edit', { survey: survey.id, section: section.id, page: page.id, question: nextQuestion.id}) }}">
                        <span>{{ nextQuestion.code is not empty ? nextQuestion.code|upper : nextQuestion.title|capitalize  }}</span>
                    </a>
                {% else %}
                    <span class="badge badge-secondary px-3">FIN</span>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-5 px-0">
                <span class="badge badge-success" title="Pregunta de {{ q.typeName }}">{{ q|firstLetterType }}</span>
                <a class="link" title="Editar pregunta" href="{{ path('dsy_survey_section_page_question_edit', { survey: survey.id, section: section.id, page: page.id, question: q.id}) }}">
                    <span>{{ q.code is not null ? q.code|upper : q.title|capitalize }}</span>
                </a>
            </div>
            <div class="col-2 text-center px-0">&nbsp;</div>
            <div class="col-5">&nbsp;</div>
        </div>
        {% for alt in q.alternativesEnabled %}
            {% set nextQuestion = nextQuestionForAlternative(alt) %}
            <div class="row">
                <div class="col-5 pl-4">
                    <span class="badge badge-info" title="Alternativa">A</span>
                    <span>{{ alt.title|upper ~ (alt.code is not empty ? ' (' ~ alt.code ~ ')' : '')|trim  }}</span>
                </div>
                <div class="col-2 text-center px-0">>></div>
                <div class="col-5 px-0 text-right">
                    {% if nextQuestion is not null %}
                        <span class="badge badge-success" title="Pregunta de {{ nextQuestion.typeName }}">{{ nextQuestion|firstLetterType }}</span>
                        <a class="link" title="Editar pregunta" href="{{ path('dsy_survey_section_page_question_edit', { survey: survey.id, section: section.id, page: page.id, question: nextQuestion.id}) }}">
                            <span>{{ nextQuestion.code is not empty ? nextQuestion.code|upper : nextQuestion.title|capitalize  }}</span>
                        </a>
                    {% else %}
                        <span class="badge badge-secondary px-3">FIN</span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endfor %}

Resources/views/Web/flow_exception/index.html.twig
{% extends '@DSYSurvey/Web/question/edit.html.twig' %}

{% block surveyBreadcrumb %}
    {{ parent() }}
    <li class="breadcrumb-item">
        <a href="{{ path('dsy_survey_section_page_question_flow_exception_index', { question: question.id}) }}">{{ 'Excepciones de flujo'|trans }}</a>
    </li>
{% endblock %}

{% block surveyBody %}
    <div class="row mb-5">
        <div class="col col-md-12">
            <h2>EXCEPCIONES DE FLUJO</h2>
            {% if backlUrl %}
            <a role="button" class="link text-dark" href="{{ backlUrl }}">
                <span>{{ 'Volver'|trans|upper }}</span>
            </a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Listado</div>
                    {# <div class="card-title">
                        
                    </div> #}
                </div>
                {% if exceptions|length == 0 %}
                    <div class="card-body">
                        <div class="alert alert-warning" role="alert">
                            <span>No hay excepiones de flujo registradas para esta pregunta.</span>
                        </div>
                    </div>
                {% else %}
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Alternativa</th>
                                    <th>Siguiente pregunta</th>
                                    <th>Creado</th>
                                    <th colspan="2"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ex in exceptions %}
                                    <tr class="{# {{ exception.id == ex.id ? 'table-warning' : '' }} #}">
                                        <td>{{ loop.index }}</td>
                                        <td>{{ ex.alternative is not empty ? ex.alternative.title : ' - '  }}</td>
                                        <td>
                                            {% if ex.newFlow is not empty %}
                                                <span class="badge badge-secondary mr-2" title="{{ ex.newFlow.typeName }}">{{ ex.newFlow|firstLetterType }}</span>
                                                <span title="{{ ex.newFlow.title }}">{{ ex.newFlow.code is not empty ? ex.newFlow.code : ex.newFlow.title }}</span>
                                            {% else %}
                                                <span class="badge badge-dark">FIN</span>
                                            {% endif %}
                                        </td>
                                        <td>{{ ex.createdAt|date('d/m/Y') }}</td>
                                        <td class="text-right">
                                            <a role="button" class="btn btn-warning btn-sm" href="{{ path('dsy_survey_section_page_question_flow_exception_edit', { question: question.id, exception: ex.id }) }}">
                                                <span>Editar</span>
                                            </a>
                                            <a role="button" class="btn btn-danger btn-sm" onclick="javascript: return confirm('¿Esta seguro?');" href="{{ path('dsy_survey_section_page_question_flow_exception_delete', { question: question.id, exception: ex.id }) }}">
                                                <span>Borrar</span>
                                            </a>
                                        </td>
                                        <td style="width: 60px;" class="text-right">
                                            {% if exception.id == ex.id %}
                                                <h4><span class="badge badge-warning">>></span></h4>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col">
            <div class="card {{ exception.id is null ? '' : 'border-warning' }}">
                {{ form_start(form) }}
                <div class="card-header ">
                    <div class="card-title">{{ (exception.id is null ? 'Nueva' : 'Editando') ~ ' Excepción' }}</div>
                </div>
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col">
                            <small class="mb-3">
                                <span><strong class="mr-2">PREGUNTA</strong>{{ ((question.code is not empty ? '(' ~ question.code ~ ') ') ~ question.title)|upper }}</span>
                                <span class=" d-block text-muted">{{ ('De tipo ' ~ question.typeName)|upper }}</span>
                            </small>
                        </div>
                    </div>
                    {{ form_widget(form) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}