Entity/SurveyInterface.php
<?php

namespace DSYSurveyBundle\Entity;

use Doctrine\Common\Collections\Collection;

/**
 * @author snake77se at dsarhoya.cl
 */
interface SurveyInterface
{
    const STATE_EDIT = 'edit';
    const STATE_PUBLISHED = 'published';
    const STATE_FINISHED = 'finished';

    /**
     * Get ID Survey.
     *
     * @return int
     */
    public function getId();

    /**
     * Get name Survey.
     *
     * @return string
     */
    public function getName();

    /**
     * Get description Survey.
     *
     * @return string
     */
    public function getDescription();

    /**
     * Set code at Survey.
     *
     * @param string|null $code
     *
     * @return SurveyInterface
     */
    public function setCode($code = null);

    /**
     * Get description Survey.
     *
     * @return string|null
     */
    public function getCode();

    /**
     * Get state Survey.
     *
     * @return string
     */
    public function getState();

    /**
     * Get published at Survey.
     *
     * @return \DateTime
     */
    public function getPublishedAt();

    /**
     * Get disabled at Survey.
     *
     * @return \DateTime
     */
    public function getStartedAt();

    /**
     * Get disabled at Survey.
     *
     * @return \DateTime
     */
    public function getFinishedAt();

    /**
     * Get created at Survey.
     *
     * @return \DateTime
     */
    public function getCreatedAt();

    /**
     * Get updated at Survey.
     *
     * @return \DateTime
     */
    public function getUpdatedAt();

    /**
     * Get states at Survey.
     *
     * @return array
     */
    public static function getStates();

    /**
     * Get label state at Survey.
     *
     * @return string
     */
    public function getStateLabel();

    /**
     * Get surveyAnswers at Survey.
     *
     * @return Collection
     */
    public function getSurveyAnswers();

    /**
     * Get sections at Survey.
     *
     * @return Collection
     */
    public function getSections();

    /**
     * Get sections at Survey.
     *
     * @return Collection
     */
    public function getEnabledSections();

    /**
     * add section at Survey.
     *
     * @return SurveyInterface
     */
    public function addSection(Section $section);

    /**
     * remove section at Survey.
     *
     * @return bool
     */
    public function removeSection(Section $section);

    /**
     * Set state at Survey.
     *
     * @param string $state
     *
     * @return SurveyInterface
     */
    public function setState($state);

    /**
     * Set name at Survey.
     *
     * @return SurveyInterface
     */
    public function setName($name);

    /**
     * Set publishedAt at Survey.
     *
     * @param \DateTime $publishedAt
     *
     * @return SurveyInterface
     */
    public function setPublishedAt($publishedAt);

    /**
     * Set finishedAt at Survey.
     *
     * @param \DateTime $finishedAt
     *
     * @return SurveyInterface
     */
    public function setFinishedAt($finishedAt);

    /**
     * Set startedAt at Survey.
     *
     * @param \DateTime $startedAt
     *
     * @return SurveyInterface
     */
    public function setStartedAt($startedAt);

    /**
     * Set description at Survey.
     *
     * @param string $description
     *
     * @return SurveyInterface
     */
    public function setDescription($description);
}

Resources/views/Web/page/edit.html.twig
{% extends '@DSYSurvey/Web/page/index.html.twig' %}

{% block surveyBreadcrumb %}
    {{ parent() }}
    <li class="breadcrumb-item">
        <a href="{{ path('dsy_survey_section_page_edit', {survey: survey.id, section: section.id, page: page.id}) }}"><strong>{{ page.title }}</strong></a>
    </li>
{% endblock %}

{% block surveyBody %}

    <div class="row mb-5">
        <div class="col ">
            <h2>{{ ((page.id is not null ? 'Editando' : 'Creando') ~ ' página' )|upper }} </h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm col-md-12">
            {{ form(form) }}
        </div>
    </div>
{% endblock %}

Resources/views/Web/page/index.html.twig
{% extends '@DSYSurvey/Web/section/edit.html.twig' %}

{% block surveyBreadcrumb %}
    {{ parent() }}
    <li class="breadcrumb-item">
        <a href="{{ path('dsy_survey_section_page_index', {survey: survey.id, section: section.id}) }}">{{ 'Páginas'|trans }}</a>
    </li>
{% endblock %}

{% block surveyBody %}
    <div class="row">
        <div class="col-sm col-md-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Estado</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for page in pages %}
                        <tr>
                            <td>{{ page.title }}</td>
                            <td>{{ page.enabled ? 'Habilitada' : 'Deshabilitada' }}</td>
                            <td>
                                <a href="{{ path('dsy_survey_section_page_edit', {survey: survey.id, section: section.id, page: page.id}) }}">Editar</a>
                                &nbsp;
                                <a href="{{ path('dsy_survey_section_page_question_index', {survey: survey.id, section: section.id, page: page.id}) }}">Preguntas</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if app.request.get('all') %}
                    <a href="{{ path('dsy_survey_section_page_index', {survey: survey.id, section: section.id}) }}">Ver solo habilitadas</a>
                {% else %}
                    <a href="{{ path('dsy_survey_section_page_index', {survey: survey.id, section: section.id, all: 1}) }}">Ver todas</a>
                {% endif %}
                
            </div>
            <a href="{{ path('dsy_survey_section_page_edit', {survey: survey.id, section: section.id}) }}" class="btn btn-info">Crear página</a>
        </div>
    </div>
{% endblock %}